#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# yabai -m config external_bar               all:40:0       \
#                 menubar_opacity            0.0            \
#                 mouse_follows_focus        off            \
#                 focus_follows_mouse        off            \
#                 window_animation_duration  0.00           \
#                 window_zoom_persist        off            \
#                 window_placement           second_child   \
#                 insert_feedback_color      0xff9dd274     \
#                 split_ratio                0.50           \
#                 auto_balance               off            \
#                 mouse_modifier             fn             \
#                 mouse_action1              move           \
#                 mouse_action2              resize         \
#                 mouse_drop_action          swap           \
#                 top_padding                8              \
#                 bottom_padding             8              \
#                 left_padding               8              \
#                 right_padding              8              \
#                 window_gap                 10             \
#     		layout                     bsp            \

# yabai -m rule --add app="^Arc$" space=1
yabai -m rule --add app="^Google Chrome$" space=1
yabai -m rule --add app="^Obsidian$" space=2
yabai -m rule --add app="^Discord$" space=3
yabai -m rule --add app="^Spotify$" space=4
yabai -m rule --add app="^Kitty$" space=5
yabai -m rule --add app="^Code$" space=6
yabai -m rule --add app="^IntelliJ IDEA$" space=6
yabai -m rule --add app="^PyCharm$" space=6
yabai -m rule --add app="^Xcode$" space=6
yabai -m rule --add app="^Trae$" space=6

echo "yabai configuration loaded.."
